// Naming:
// ACTION_ENTITY_RESULT

export const SET_API_REQUEST = 'SET_API_REQUEST';
export const SET_API_SUCCESS = 'SET_API_SUCCESS';
export const SET_API_FAILURE = 'SET_API_FAILURE';
export const SET_API_PAGINATOR = 'SET_API_PAGINATOR';

export const CLEAR_API_STATE = 'CLEAR_API_STATE';
