export const CREATE_USER = 'CREATE_USER';

export const LOGIN_USER = 'LOGIN_USER';
export const GET_USER = 'GET_USER';
export const GET_LOGGINED_USER = 'GET_LOGGINED_USER';
export const USER_ACTIVATE = 'USER_ACTIVATE';
export const UPDATE_USER = 'UPDATE_USER';
export const RECOVERY_PASSWORD = 'RECOVERY_PASSWORD';
export const USER_LOADED = 'USER_LOADED';

export const CLEAR_USER_FORM = 'CLEAR_USER_FORM';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CLEAR_DATA_STATE = 'CLEAR_DATA_STATE';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPLOAD_PHOTO_ME = 'UPLOAD_PHOTO_ME';
export const UPLOAD_PHOTO_CLINIC = 'UPLOAD_PHOTO_CLINIC';
export const GET_PHOTOS_ME = 'GET_PHOTOS_ME';
export const GET_PHOTOS_CLINIC = 'GET_PHOTOS_CLINIC';
